import { Listing, Parcel } from "./types";

export const parcels: Parcel[] = [
  {
    apn: "100-200-01",
    address: "123 Main St, Metro City",
    zoningDistrict: "R-3",
    allowedUses: ["Multifamily", "ADU", "Townhome"],
    maxHeightFt: 45,
    frontSetbackFt: 15,
    sideSetbackFt: 5,
    rearSetbackFt: 15,
    far: 2.0,
    lotCoverage: 0.6,
    maxUnits: 18,
    lotAreaSqft: 12000,
    lotWidthFt: 100,
    lotDepthFt: 120,
    risk: { floodZone: "X", wildfire: "low", heatRisk: "medium" },
  },
  {
    apn: "100-200-02",
    address: "55 Oak Ave, Metro City",
    zoningDistrict: "MU-2",
    allowedUses: ["Mixed-use", "Retail", "Multifamily"],
    maxHeightFt: 65,
    frontSetbackFt: 10,
    sideSetbackFt: 0,
    rearSetbackFt: 10,
    far: 3.5,
    lotCoverage: 0.8,
    maxUnits: 42,
    lotAreaSqft: 20000,
    lotWidthFt: 125,
    lotDepthFt: 160,
    risk: { floodZone: "AE", wildfire: "low", heatRisk: "high" },
  },
];

export const listings: Listing[] = [
  {
    id: "l1",
    address: "12 Cedar Ln, Metro",
    price: 845000,
    beds: 3,
    baths: 2,
    sqft: 1820,
    yearBuilt: 1928,
    styleLabel: "Craftsman",
    styleConfidence: 0.79,
    clues: ["Exposed rafters", "Tapered columns", "Wide front porch"],
    neighborhood: "North Park",
  },
  {
    id: "l2",
    address: "81 Skyline Dr, Metro",
    price: 1295000,
    beds: 4,
    baths: 3,
    sqft: 2550,
    yearBuilt: 1964,
    styleLabel: "Mid-Century Modern",
    styleConfidence: 0.84,
    clues: ["Low-pitched roof", "Clerestory windows", "Open plan"],
    neighborhood: "Canyon View",
  },
  {
    id: "l3",
    address: "9 Harbor Ct, Metro",
    price: 940000,
    beds: 3,
    baths: 2,
    sqft: 1740,
    yearBuilt: 1998,
    styleLabel: "Contemporary",
    styleConfidence: 0.62,
    clues: ["Flat planes", "Large glazing"],
    neighborhood: "Marina East",
  },
  {
    id: "l4",
    address: "303 Willow St, Metro",
    price: 715000,
    beds: 2,
    baths: 1,
    sqft: 1320,
    yearBuilt: 1911,
    styleLabel: "Victorian",
    styleConfidence: 0.73,
    clues: ["Ornate trim", "Bay windows", "Steep gable"],
    neighborhood: "Old Town",
  },
];
